### ISSUE TITLE
can't export glb after 3d asset preview generation

### ISSUE THREAD

**Issue by virusvjvisuals** [pinokiofactory/TRELLIS#3]
Hey There!!

I 'm a bit confused about this issue, I tried this install from pinokio 2 days befoire and got errors about spconv gave no outputs.... 
Saw there where some updates on the code so i did the install again yesterday from scratch , and it worked perfectly during multiple tests, and produced excellent results really fast!

I launched Trellis this evening again, and multiple errors during the generation process, which was sluggish to output video, and althought  it produces it slowly, the "export glb"  button doesn't output anything, nor in the terminal. (last line is about the preview rendering itérations, and after nothing happens anymore. 

I tried a reset of the pinokio container, another clean install, then an update, but still got the same issues...

}
Traceback (most recent call last):
  File "C:\Users\virus\pinokio\api\TRELLIS.git\app\env\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\virus\pinokio\api\TRELLIS.git\app\env\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\virus\pinokio\api\TRELLIS.git\app\env\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "C:\Users\virus\pinokio\api\TRELLIS.git\app\env\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\Users\virus\pinokio\api\TRELLIS.git\app\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\virus\pinokio\api\TRELLIS.git\app\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
  File "C:\Users\virus\pinokio\api\TRELLIS.git\app\env\lib\site-packages\anyio\_backends\_asyncio.py", line 1005, in run
    result = context.run(func, *args)
  File "C:\Users\virus\pinokio\api\TRELLIS.git\app\env\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\virus\pinokio\api\TRELLIS.git\app\app.py", line 136, in extract_glb
    gs, mesh, trial_id = unpack_state(state)
  File "C:\Users\virus\pinokio\api\TRELLIS.git\app\app.py", line 60, in unpack_state
    aabb=state['gaussian']['aabb'],
TypeError: 'NoneType' object is not subscriptable

and also warnings about Xformers available at multiple locations.
also a warning about CUDA_ARCH_LIST not defined on Os 'env Path ...

is there a way to rollback to yesterday's state of the container ? (other than a DeLorean ?) 

Thanks for your work on this tool, it s really neat !!

**Comment by Deathdadev** [comment]
Hey I am sorry to hear that it randomly stopped working. Just to clarify, what branch were you using originally when it was working, and what branch did you update to? Knowing this information, I can help find what version was working for you before and "undo" the changes

**Comment by virusvjvisuals** [comment]
Hi there , 
Thanks for your advice and sorry for the latency too
finally, i deleted the complete Trellis app, and reinstalled it from scratch, and it seems to work now ! 
I m wondering about the fact that  on my first install of trellis, it was working perfectly  at the beginning and with a lot of test renders too, and it was REALLY fast to generate the preview video, but also exporting the Glb file..
now it works again with the fresh install, but it s soooo long to generate the preview... and exporting the glb file takes like 45 min at least now... 

![image](https://github.com/user-attachments/assets/cfcf8a9d-cc70-4dd7-a217-14d9e5c1389b)
![image](https://github.com/user-attachments/assets/50c14777-21c2-4c2e-bf98-2833c3df5b86)

couldn't fix the issues shown in the 2 captures above...
i ve set theTORCH_CUDA_ARCH_LIST to my system path with the value "8.9", but still got , also tried to add it to the Trellis env , with no succes for now .. 
i wonder about a way to fix this, and hope this may accelerate the Trellis tasks too, would be really great

Thanks by advance, for any helpful advice ;) 
the initial issue of this ticket is solved though, feel free to close the thread 
thanks again
