### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by rktvr** [pinokiofactory/TRELLIS#5]
ENOENT: no such file or directory, stat 'E:\pinokio\api\TRELLIS.git\{{input.event[0]}}'

and

E:\pinokio\api\TRELLIS.git\app>conda_hook && conda deactivate && conda deactivate && conda deactivate &
& conda activate base && E:\pinokio\api\TRELLIS.git\app\env\Scripts\activate E:\pinokio\api\TRELLIS.git
\app\env && python -c "import torch; print(\";\".join([arch.replace(\"sm_\", \"\") for arch in torch.cu
da.get_arch_list()]))" && python app.py

Traceback (most recent call last):
  File "<string>", line 1, in <module>      
ModuleNotFoundError: No module named 'torch'

**Comment by rktvr** [comment]
during install, it also mentions 'uv' module not found.

seems like a recent change broke stuff badly

**Comment by HansHunz** [comment]
Having the same issues.

**Comment by Deathdadev** [comment]
This project is for a beta version of pinokio and uses newer upcoming features in pinokio so that is probably why it is failing for you guys. If you are keen to use it, this project is still somewhat being worked on, but you can download the newer beta releases from here to try it out: https://github.com/cocktailpeanutlabs/p2/releases

**Comment by HansHunz** [comment]
> This project is for a beta version of pinokio and uses newer upcoming features in pinokio so that is probably why it is failing for you guys. If you are keen to use it, this project is still somewhat being worked on, but you can download the newer beta releases from here to try it out: https://github.com/cocktailpeanutlabs/p2/releases

Thank you.  This worked!

**Comment by rktvr** [comment]
indeed, it works with the beta version.

**Comment by Mixomo** [comment]
not work for me :( 

when I upload the image and hit generate, it renders and when it finishes rendering it jumps this error and does not show the video.

`Sampling:   8%|██████████████▌                                                                                                                                                                | 1/12 [00:00<00:02,  3.88it/s]
Sampling: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.10it/s]
Sampling: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.54it/s]
Rendering: 120it [00:01, 95.72it/s]
Traceback (most recent call last):
  File "I:\pinokio_home\api\TRELLIS\app\env\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "I:\pinokio_home\api\TRELLIS\app\env\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "I:\pinokio_home\api\TRELLIS\app\env\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "I:\pinokio_home\api\TRELLIS\app\env\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "I:\pinokio_home\api\TRELLIS\app\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "I:\pinokio_home\api\TRELLIS\app\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
  File "I:\pinokio_home\api\TRELLIS\app\env\lib\site-packages\anyio\_backends\_asyncio.py", line 1005, in run
    result = context.run(func, *args)
  File "I:\pinokio_home\api\TRELLIS\app\env\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "I:\pinokio_home\api\TRELLIS\app\app.py", line 115, in image_to_3d
    video_geo = render_utils.render_video(outputs['mesh'][0], num_frames=120)['normal']
  File "I:\pinokio_home\api\TRELLIS\app\trellis\utils\render_utils.py", line 96, in render_video
    return render_frames(sample, extrinsics, intrinsics, {'resolution': resolution, 'bg_color': bg_color}, **kwargs)
  File "I:\pinokio_home\api\TRELLIS\app\trellis\utils\render_utils.py", line 62, in render_frames
    renderer = MeshRenderer()
  File "I:\pinokio_home\api\TRELLIS\app\trellis\renderers\mesh_renderer.py", line 56, in __init__
    self.glctx = dr.RasterizeCudaContext(device=device)
  File "I:\pinokio_home\api\TRELLIS\app\env\lib\site-packages\nvdiffrast\torch\ops.py", line 184, in __init__
    self.cpp_wrapper = _get_plugin().RasterizeCRStateWrapper(cuda_device_idx)
  File "I:\pinokio_home\api\TRELLIS\app\env\lib\site-packages\nvdiffrast\torch\ops.py", line 125, in _get_plugin
    torch.utils.cpp_extension.load(name=plugin_name, sources=source_paths, extra_cflags=common_opts+cc_opts, extra_cuda_cflags=common_opts+['-lineinfo'], extra_ldflags=ldflags, with_cuda=True, verbose=False)
  File "I:\pinokio_home\api\TRELLIS\app\env\lib\site-packages\torch\utils\cpp_extension.py", line 1314, in load
    return _jit_compile(
  File "I:\pinokio_home\api\TRELLIS\app\env\lib\site-packages\torch\utils\cpp_extension.py", line 1746, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "I:\pinokio_home\api\TRELLIS\app\env\lib\site-packages\torch\utils\cpp_extension.py", line 2140, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: DLL load failed while importing nvdiffrast_plugin: No se puede encontrar el módulo especificado.`
