### ISSUE TITLE
Works then stops working - can't install it anymore

### ISSUE THREAD

**Issue by hansolocambo** [pinokiofactory/TRELLIS#6]
I use Pinokio 3.0.31 (from https://github.com/pinokiocomputer/pinokio)

Trellis installed fine. Worked for a day or two, then didn't want to start anymore. I uninstalled it a few times because of that. Weirdly enough a fresh setup of just Trellis and it would work again, until it doesn't start anymore... again. 

But this morning, same issue. But now I can't even install it anymore. CVould you please tell me what you think of this error message ? Having to reinstall all Pinokio and the other stable AI apps I use, just because this integration of Trellis seems unstable it kind of problematic :/

![image](https://github.com/user-attachments/assets/1581e11a-4fc1-498c-bf72-390c9d9e4bb4)

Thanks.

**Comment by hansolocambo** [comment]
Just for info, I removed pinokio 3.0.31 from https://github.com/pinokiocomputer/pinokio, and installed the latest version 3.0.37, from https://github.com/cocktailpeanutlabs/p2, just in case... But error messages, even with a clean install of everything, ending up being the same. 
Between yesterday when I was using Trellis all day long and today when it stopped working, I did nothing more than sleeping :/

**Comment by hansolocambo** [comment]
Just for info, I removed pinokio 3.0.31 from https://github.com/pinokiocomputer/pinokio, and installed version 3.0.37, from https://github.com/cocktailpeanutlabs/p2, just in case... But error messages, even with a clean install of everything, ended up being the same.

**Comment by cmackenna** [comment]
Same problem here:
ValueError: not enough values to unpack (expected 8, got 4)

**Comment by hansolocambo** [comment]
> Same problem here: ValueError: not enough values to unpack (expected 8, got 4)

I ended up installing that today: [Trellis-Stable-Projectorz](https://github.com/IgorAherne/trellis-stable-projectorz/releases/tag/latest)

Click run.bat and that's all. Installed. Worked instantly for me. !!!Careful!!! When you see in the Command Prompt of the run.bat the following sentence: "Installation Complete Successfully!" do NOT close the window. Wait, it's not done yet :/ It is only done running when you'll see "Press any key to continue". 

There's no WebUI which sucks a bit. But it works fine. To use it once installed: 
1- Put an image namd **T.png** in the folder **\trellis-stable-projectorz\assets\example_image**
2- Run again the same file run.bat. This will process T.png in a command prompt. 
3- Once it's done you'll have *.glb (3D, blender, etc.), .ply (point cloud), and preview videos. 

The few models I posted [here](https://sketchfab.com/nexinformatique/models), from the gaming chair (look at the details in this one  !) to the last one with 3 cars, it's all done with Trellis. 

Cheers. Hope it'll also work for you.

**Comment by cmackenna** [comment]
Thanks for the workaround info.  I haven't tried this yet.  I'm hoping this awesome tool will work properly with Pinokio soon, including UI.  I'll resort to trying your workaround if nothing else pans out soon.

**Comment by hansolocambo** [comment]
EDIT: script update today: 2025/01/03
Crashes during setup. This crap script simply doesn't work.

E:\pinokio\api\TRELLIS.git\app>conda_hook && conda deactivate && conda deactivate && conda deactivate && conda activate base && E:\pinokio\api\TRELLIS.git\app\env\Scripts\activate E:\pinokio\api\TRELLIS.git\app\env && uv pip install -r ../requirements.txt
error: Expected `--hash`, found `"--no-build-isolation"` at ../requirements.txt:28:56.

**Comment by cmackenna** [comment]
Script update 2025/01/03 doesn't work for me either, fails immediately: (I do hope this gets sorted out)

Expected --hash, found "--no-build-isolation" at ../requirements.txt:28:56

Microsoft Windows 11 [Version 10.0.26100.2605]
AMD Ryzen 9 5900X 64 GB
NVIDIA GeForce RTX 3090 24GB

**Comment by Deathdadev** [comment]
> This error was a mistake on my behalf. I have fixed this issue now, so please update your installation and try again. Fixed in [this commit](https://github.com/pinokiofactory/TRELLIS/commit/ba04408e6a37b0336936fe78e10876f396dcb7c6)

Hello everyone, I apologize for not addressing this issue earlier. The message above is from [here](https://github.com/pinokiofactory/TRELLIS/issues/8#issuecomment-2571505322). The errors you have been experiencing were due to a mistake in the code while updating it to work on both Linux and Windows. Please update your version of Trellis, and this issue should be resolved:

**Comment by cmackenna** [comment]
Thanks for trying to get this to work for us.  I tried your installer again today and it doesn't work for me. 
Pinokio-3.2.0
Microsoft Windows 11 [Version 10.0.26100.2605]
AMD Ryzen 9 5900X 64 GB
NVIDIA GeForce RTX 3090 24GB

:
:

Microsoft Windows [Version 10.0.26100.2605]
(c) Microsoft Corporation. All rights reserved.

C:\pinokio\api\TRELLIS.git\app>conda_hook && conda deactivate && conda deactivate && conda deactivate && conda activate base && C:\pinokio\api\TRELLIS.git\app\env\Scripts\activate C:\pinokio\api\TRELLIS.git\app\env && uv pip install -r ../requirements.txt
Using Python 3.10.16 environment at: env
 Updated https://github.com/NVlabs/nvdiffrast.git (729261d)
Updating https://github.com/sdbds/diff-gaussian-rasterization (HEAD)
 Updated https://github.com/JeffreyXiang/diffoctreerast.git (b09c20b)
⠙ Resolving dependencies...                                                                                                                                                                        error: The build backend returned an error
  Caused by: Call to `setuptools.build_meta:__legacy__.build_wheel` failed (exit code: 1)

[stderr]
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\Users\Chris\AppData\Local\uv\cache\builds-v0\.tmp94xGtR\lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=[])
  File "C:\Users\Chris\AppData\Local\uv\cache\builds-v0\.tmp94xGtR\lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
    self.run_setup()
  File "C:\Users\Chris\AppData\Local\uv\cache\builds-v0\.tmp94xGtR\lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
    super().run_setup(setup_script=setup_script)
  File "C:\Users\Chris\AppData\Local\uv\cache\builds-v0\.tmp94xGtR\lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
    exec(code, locals())
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'torch'

hint: This error likely indicates that `git+https://github.com/JeffreyXiang/diffoctreerast.git` depends on `torch`, but doesn't declare it as a build dependency. If `git+https://github.com/JeffreyXiang/diffoctreerast.git` is a first-party package, consider adding `torch` to its `build-system.requires`. Otherwise, `uv pip install torch` into the environment and re-run with `--no-build-isolation`.

**Comment by cmackenna** [comment]
Interestingly, if I edit your install.js and remove 'uv' from 'uv pip install -r ../requirements.txt' the install completes and the TRELLIS UI loads, but unfortunately fails during generation.

**Comment by cmackenna** [comment]
Pinokio-3.2.0
Microsoft Windows 11 [Version 10.0.26100.2605]
AMD Ryzen 9 5900X 64 GB
NVIDIA GeForce RTX 3090 24GB

UPDATE:  I finally got your TRELLIS installer working for me.  Yay!  I'm super happy TRELLIS is working in Pinokio browser now.

I'm not sure exactly what fixed it for me.  I had uninstalled Visual Studio 2022 pro and 2019 pro trials from my system.  I had manually re-installed uv.  I had manually re-installed Visual Studio Build Tools 2019.  I had run your installer again from scratch.  All of a sudden TRELLIS  works perfectly.  I can't close this issue out because I didn't create it, but I did give your project a star.  Thank you!

**Comment by hansolocambo** [comment]
Well it gives some hope :/ Thanks for sharing your experience. As far as I'm concerned each update give its own error. Latest from yesterday gives me that: 

 Start  View File
 (4/5) shell.run
{"venv":"env","path":"app","message":["uv pip install -r ../requirements.txt","uv pip install huggingface_hub hf_transfer"]}
ERROR
Microsoft Windows [Version 10.0.22631.4602]
(c) Microsoft Corporation. All rights reserved.

E:\pinokio\api\TRELLIS.git\app>conda_hook && conda deactivate && conda deactivate && conda deactivate && conda activate base && E:\pinokio\api\TRELLIS.git\app\env\Scripts\activate E:\pinokio\api\TRELLIS.git\app\env && uv pip install -r ../requirements.txt
Using Python 3.10.16 environment at: env
 Updated https://github.com/NVlabs/nvdiffrast.git (729261d)
 Updated https://github.com/JeffreyXiang/diffoctreerast.git (b09c20b)
Updating https://github.com/sdbds/diff-gaussian-rasterization (HEAD)
⠸ Resolving dependencies...                                                                                                                           
error: The build backend returned an error
  Caused by: Call to `setuptools.build_meta:__legacy__.build_wheel` failed (exit code: 1)

[stderr]
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\Users\hanso\AppData\Local\uv\cache\builds-v0\.tmpyGpvvZ\lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=[])
  File "C:\Users\hanso\AppData\Local\uv\cache\builds-v0\.tmpyGpvvZ\lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
    self.run_setup()
  File "C:\Users\hanso\AppData\Local\uv\cache\builds-v0\.tmpyGpvvZ\lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
    super().run_setup(setup_script=setup_script)
  File "C:\Users\hanso\AppData\Local\uv\cache\builds-v0\.tmpyGpvvZ\lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
    exec(code, locals())
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'torch'

hint: This error likely indicates that `git+https://github.com/JeffreyXiang/diffoctreerast.git` depends on `torch`, but doesn't declare it as a build dependency. If `git+https://github.com/JeffreyXiang/diffoctreerast.git` is a first-party package, consider adding `torch` to its `build-system.requires`. Otherwise, `uv pip install torch` into the environment and re-run with `--no-build-isolation`.

(env) (base) E:\pinokio\api\TRELLIS.git\app>

Aka: still doesn't install.
